### **Data Auditing and Missingness Mechanisms**

#### **Step 1: Install and Load the Required Libraries for Data Profiling and EDA**

In [1]:
!pip install fg-data-profiling
#!pip install ydata-profiling

Requirement already satisfied: fg-data-profiling in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (4.19.1)
Requirement already satisfied: scipy<1.17,>=1.8 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from fg-data-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from fg-data-profiling) (2.3.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from fg-data-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from fg-data-profiling) (2.13.4)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from fg-data-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from fg-data-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from fg-data-profiling) (2.3.5)
Requirement already satisfied: minify-html>=0.15.0 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from fg-data-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from fg-data-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from fg-data-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from fg-data-profiling) (2.34.2)
Requirement already satisfied: tqdm<5,>=4.66.3 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from fg-data-profiling) (4.70.0)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from fg-data-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from fg-data-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from fg-data-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from fg-data-profiling) (4.6.0)
Requirement already satisfied: imagehash==4.3.2 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from fg-data-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from fg-data-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from fg-data-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from fg-data-profiling) (0.62.1)
Requirement already satisfied: PyWavelets in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from imagehash==4.3.2->fg-data-profiling) (1.9.0)
Requirement already satisfied: pillow in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from imagehash==4.3.2->fg-data-profiling) (12.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from jinja2<3.2,>=3.1.6->fg-data-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\User\AppData\Roaming\Python\Python312\site-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (26.3)
Requirement already satisfied: pyparsing>=2.3.1 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\User\AppData\Roaming\Python\Python312\site-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from numba<0.63,>=0.60->fg-data-profiling) (0.45.1)
Requirement already satisfied: pytz>=2020.1 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->fg-data-profiling) (2026.3.post1)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->fg-data-profiling) (2026.3)
Requirement already satisfied: joblib>=0.14.1 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from phik<0.13,>=0.12.5->fg-data-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pydantic<3,>=2->fg-data-profiling) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pydantic<3,>=2->fg-data-profiling) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in C:\Users\User\AppData\Roaming\Python\Python312\site-packages (from pydantic<3,>=2->fg-data-profiling) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pydantic<3,>=2->fg-data-profiling) (0.4.3)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from requests<3,>=2.32.0->fg-data-profiling) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from requests<3,>=2.32.0->fg-data-profiling) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from requests<3,>=2.32.0->fg-data-profiling) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from requests<3,>=2.32.0->fg-data-profiling) (2026.7.22)
Requirement already satisfied: patsy>=0.5.6 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from statsmodels<1,>=0.13.2->fg-data-profiling) (1.0.2)
Requirement already satisfied: colorama in C:\Users\User\AppData\Roaming\Python\Python312\site-packages (from tqdm<5,>=4.66.3->fg-data-profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (3.6.1)
Requirement already satisfied: puremagic in C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (2.2.0)
Requirement already satisfied: six>=1.5 in C:\Users\User\AppData\Roaming\Python\Python312\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->fg-data-profiling) (1.17.0)

In [2]:
#!pip install "setuptools<81"

#### **Step 2: Load the Data Profiling Libraries**

In [3]:
import pandas as pd
import numpy as np
import webbrowser
import data_profiling
from data_profiling import ProfileReport
#from fg_data_profiling import ProfileReport

c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

#### **Step 3: Loadi the Required Dataset**

In [4]:
df = pd.read_csv("Business_Data_Quality_Issues.csv")
df.head(10)

,OrderID,CustomerID,FirstName,LastName,Gender,Age,Region,ProductCategory,Quantity,UnitPrice,...,SalesRep,PaymentMethod,CustomerSegment,City,OrderDate,Email,Phone,Rating,Comments,Revenue
0,ORD000001,CUST46472,Kelly,Baker,Male,53,South,Sports,10,2775.16,...,Nancy,Bank Transfer,Wholesale,Nairobi,2025-05-24,vincent2294@gmail.com,0713301123,4,Late delivery,25253.96
1,ORD000002,CUST28725,Adam,Jordan,NaN,39,South,Sports,6,688.75,...,Tabitha,Cash,NaN,NaN,2024-09-18,marilyn547@gmail.com,0774478500,5,Late delivery,2810.10
2,ORD000003,CUST11646,Paul,Adams,Female,43,West,Health & Beauty,17,2327.62,...,Ian,Mobile Money,SME,Malindi,2023-07-07,NaN,0710826636,3,Highly recommended,24928.81
3,ORD000004,CUST66427,Chris,Fox,Male,75,East,Furniture,5,1477.19,...,Brian,Mobile Money,Wholesale,Naivasha,2024-02-11,charlotte217@gmail.com,0761837969,5,Product damaged,5391.74
4,ORD000005,CUST55342,Nancy,Njoroge,Male,71,East,NaN,-16,253.64,...,Steve,Bank Transfer,SME,embu,2024-02-15,logan1615@gmail.com,0752633078,4,Average experience,-3003.10
5,ORD000006,CUST98919,Alex,Ryan,Female,69,Central,Home Appliances,18,2179.50,...,Paul,Debit Card,Government,nyeri,2024-03-20,kyle6091@gmail.com,0773139931,4,Wrong item,25107.84
6,ORD000007,CUST10078,Thomas,Harris,Female,38,West,Home Appliances,20,1108.99,...,Martin,Credit Card,Retail,Kitale,2024-06-04,billy9665@gmail.com,0775325391,4,Late delivery,21736.20
7,ORD000008,CUST11133,Lisa,Webb,Male,50,Central,Electronics,9,1811.75,...,Edwin,Debit Card,Retail,Mombasa,2025-03-25,alex9174@gmail.com,0759815442,1,Highly recommended,10109.57
8,ORD000009,CUST32507,Angela,Brooks,Female,34,East,Furniture,11,2274.12,...,Terry,Credit Card,Wholesale,Kisii,2023-02-05,albert9355@gmail.com,0791307297,1,Average experience,24264.86
9,ORD000010,CUST79557,Olivia,Morris,Female,20,North,Automotive,1,457.26,...,Calvin,Debit Card,Wholesale,Kitale,2023-05-12,ryan7579@gmail.com,0778241027,1,Late delivery,370.38

#### **Step 4: Data Profiling**

In [5]:
profile = ProfileReport(df, title="Data Profiling Report", explorative=True)
profile.to_file("data_profiling_report.html")
webbrowser.open("data_profiling_report.html")

100%|██████████| 21/21 [00:06<00:00,  3.18it/s]7<00:01,  3.72it/s, Describe variable: Revenue]
Summarize dataset: 100%|██████████| 67/67 [00:18<00:00,  3.69it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:10<00:00, 10.03s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  1.25it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 24.21it/s]

True

#### **Step 5: Exploratory Data Analysis(EDA) and Visualization**

###### **5.1 Check the Shape of the Data**

In [6]:
df.shape

(60500, 21)

##### **5.2 Check the Data Types**

In [7]:
df.dtypes

OrderID             object
CustomerID          object
FirstName           object
LastName            object
Gender              object
Age                  int64
Region              object
ProductCategory     object
Quantity             int64
UnitPrice          float64
Discount           float64
SalesRep            object
PaymentMethod       object
CustomerSegment     object
City                object
OrderDate           object
Email               object
Phone               object
Rating               int64
Comments            object
Revenue            float64
dtype: object

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60500 entries, 0 to 60499
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          60500 non-null  object
 1   CustomerID       60500 non-null  object
 2   FirstName        57626 non-null  object
 3   LastName         57616 non-null  object
 4   Gender           57490 non-null  object
 5   Age              60500 non-null  int64
 6   Region           57469 non-null  object
 7   ProductCategory  57468 non-null  object
 8   Quantity         60500 non-null  int64
 9   UnitPrice        60500 non-null  float64
 10  Discount         60500 non-null  float64
 11  SalesRep         57479 non-null  object
 12  PaymentMethod    57485 non-null  object
 13  CustomerSegment  57478 non-null  object
 14  City             57470 non-null  object
 15  OrderDate        60500 non-null  object
 16  Email            57488 non-null  object
 17  Phone            57402 non-null  object
 18  Rating           60500 non-null  int64
 19  Comments         57497 non-null  object
 20  Revenue          60500 non-null  float64
dtypes: float64(3), int64(3), object(15)
memory usage: 9.7+ MB

##### **5.3 Check the Number of Missing Values per Variable**

In [9]:
df.isnull().sum()

OrderID               0
CustomerID            0
FirstName          2874
LastName           2884
Gender             3010
Age                   0
Region             3031
ProductCategory    3032
Quantity              0
UnitPrice             0
Discount              0
SalesRep           3021
PaymentMethod      3015
CustomerSegment    3022
City               3030
OrderDate             0
Email              3012
Phone              3098
Rating                0
Comments           3003
Revenue               0
dtype: int64

##### **5.4 Check the Percsntage of Missing Values**

In [10]:
df.isnull().mean() * 100

OrderID            0.000000
CustomerID         0.000000
FirstName          4.750413
LastName           4.766942
Gender             4.975207
Age                0.000000
Region             5.009917
ProductCategory    5.011570
Quantity           0.000000
UnitPrice          0.000000
Discount           0.000000
SalesRep           4.993388
PaymentMethod      4.983471
CustomerSegment    4.995041
City               5.008264
OrderDate          0.000000
Email              4.978512
Phone              5.120661
Rating             0.000000
Comments           4.963636
Revenue            0.000000
dtype: float64

#### **Step 6: Data Standardization**

In [11]:
df.head()

,OrderID,CustomerID,FirstName,LastName,Gender,Age,Region,ProductCategory,Quantity,UnitPrice,...,SalesRep,PaymentMethod,CustomerSegment,City,OrderDate,Email,Phone,Rating,Comments,Revenue
0,ORD000001,CUST46472,Kelly,Baker,Male,53,South,Sports,10,2775.16,...,Nancy,Bank Transfer,Wholesale,Nairobi,2025-05-24,vincent2294@gmail.com,0713301123,4,Late delivery,25253.96
1,ORD000002,CUST28725,Adam,Jordan,NaN,39,South,Sports,6,688.75,...,Tabitha,Cash,NaN,NaN,2024-09-18,marilyn547@gmail.com,0774478500,5,Late delivery,2810.10
2,ORD000003,CUST11646,Paul,Adams,Female,43,West,Health & Beauty,17,2327.62,...,Ian,Mobile Money,SME,Malindi,2023-07-07,NaN,0710826636,3,Highly recommended,24928.81
3,ORD000004,CUST66427,Chris,Fox,Male,75,East,Furniture,5,1477.19,...,Brian,Mobile Money,Wholesale,Naivasha,2024-02-11,charlotte217@gmail.com,0761837969,5,Product damaged,5391.74
4,ORD000005,CUST55342,Nancy,Njoroge,Male,71,East,NaN,-16,253.64,...,Steve,Bank Transfer,SME,embu,2024-02-15,logan1615@gmail.com,0752633078,4,Average experience,-3003.10

In [12]:
df['Gender'].value_counts()

Gender
Male       29828
Female     27362
FEMALE        70
Unknown       61
F             58
M             57
male          54
Name: count, dtype: int64

##### **6.1 Standardize Gender**

In [15]:
df['Gender'] = df['Gender'].replace({
                  'M': 'Male',
                  'male': 'Male',
                  'F': 'Female',
                  'FEMALE': 'Female'
                  })

In [16]:
df['Gender'].value_counts()

Gender
Male       29939
Female     27490
Unknown       61
Name: count, dtype: int64

##### **6.2 Standardize Region**

In [17]:
df['Region'].value_counts()

Region
North      10860
West       10742
East       10742
Central    10677
South      10618
SOUTH        783
WEST         782
EAST         770
NORTH        769
CENTRAL      726
Name: count, dtype: int64

In [18]:
df['Region'] = df['Region'].replace({
    'NORTH': 'North',
    'SOUTH': 'South',
    'EAST': 'East',
    'WEST': 'West',
    'CENTRAL': 'Central',
})

In [19]:
df['Region'].value_counts()

Region
North      11629
West       11524
East       11512
Central    11403
South      11401
Name: count, dtype: int64

##### **6.3 Standardize Product Category Column**

In [20]:
df['ProductCategory'].value_counts()

ProductCategory
Furniture              5802
Automotive             5775
Clothing               5767
Electronics            5726
Sports                 5715
Books                  5684
Health & Beauty        5588
Office Supplies        5516
Food & Beverage        5515
Home Appliances        5392
Food   &   Beverage     259
Office   Supplies       250
Health   &   Beauty     242
Home   Appliances       237
Name: count, dtype: int64

In [28]:
df['ProductCategory'] = (
    df['ProductCategory']
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
    )

In [29]:
df['ProductCategory'].value_counts()

ProductCategory
Health & Beauty    5830
Furniture          5802
Automotive         5775
Food & Beverage    5774
Clothing           5767
Office Supplies    5766
Electronics        5726
Sports             5715
Books              5684
Home Appliances    5629
Name: count, dtype: int64

In [23]:
df['PaymentMethod'].value_counts()

PaymentMethod
Mobile Money     11500
Cash             11479
Bank Transfer    11455
Debit Card       11425
Credit Card      11376
Unknown             88
Crypto              86
Cheque              76
Name: count, dtype: int64

In [24]:
df['CustomerSegment'].value_counts()

CustomerSegment
Government    11648
Wholesale     11550
Corporate     11541
SME           11386
Retail        11353
Name: count, dtype: int64

##### **6.4 Standardize the City Column**

In [25]:
df['City'].value_counts()

City
Machakos    3712
Embu        3651
Kisumu      3645
Kitale      3643
Malindi     3634
Nakuru      3586
Thika       3577
Naivasha    3558
Kisii       3557
Kericho     3557
Mombasa     3534
Nyeri       3532
Meru        3499
Eldoret     3490
Nairobi     3479
kericho      273
meru         271
kisumu       267
nakuru       267
thika        266
malindi      263
embu         260
kitale       257
nyeri        254
eldoret      254
naivasha     251
kisii        248
nairobi      239
mombasa      234
machakos     212
Name: count, dtype: int64

In [32]:
# Capitalize the first letter of each City 
df['City'] = df['City'].str.strip().str.title()

In [27]:
df['City'].value_counts()

City
Machakos    3924
Kisumu      3912
Embu        3911
Kitale      3900
Malindi     3897
Nakuru      3853
Thika       3843
Kericho     3830
Naivasha    3809
Kisii       3805
Nyeri       3786
Meru        3770
Mombasa     3768
Eldoret     3744
Nairobi     3718
Name: count, dtype: int64

In [30]:
df['SalesRep'].value_counts()

SalesRep
Lilian      1234
Zack        1213
George      1200
Samuel      1196
Henry       1193
Abel        1184
Alice       1183
Walter      1182
Oliver      1181
Quincy      1179
Ruth        1174
Paul        1172
Diana       1165
Beatrice    1164
Martin      1163
Gilbert     1162
Kevin       1161
Florence    1160
Joy         1159
Charles     1157
Valerie     1157
Kelvin      1157
Lucy        1155
Dennis      1153
Hilda       1153
Oscar       1152
Tabitha     1150
Brenda      1147
Purity      1147
Yvonne      1143
Terry       1141
Collins     1139
Ian         1139
Victor      1138
Nancy       1136
Winnie      1132
Naomi       1132
Irene       1125
Jack        1123
Mark        1120
Edwin       1117
Faith       1117
Rose        1117
Queen       1112
Xavier      1109
Steve       1105
Eric        1105
Ursula      1104
Calvin      1100
Brian       1072
Name: count, dtype: int64

##### **6.5 Put Together First and Last Name to Create a New Column Called CustomerName**

In [31]:
df['CustomerName'] = df['FirstName'] + ' ' + df['LastName']

# Place CustomerName in the position of the FirstName column
first_name_index = df.columns.get_loc('FirstName')
df.insert(first_name_index, 'CustomerName', df.pop('CustomerName'))

# Delete the FirstName and LastName columns
df.drop(['FirstName', 'LastName'], axis=1, inplace=True)
df.head(10)

,OrderID,CustomerID,CustomerName,Gender,Age,Region,ProductCategory,Quantity,UnitPrice,Discount,SalesRep,PaymentMethod,CustomerSegment,City,OrderDate,Email,Phone,Rating,Comments,Revenue
0,ORD000001,CUST46472,Kelly Baker,Male,53,South,Sports,10,2775.16,0.09,Nancy,Bank Transfer,Wholesale,Nairobi,2025-05-24,vincent2294@gmail.com,0713301123,4,Late delivery,25253.96
1,ORD000002,CUST28725,Adam Jordan,NaN,39,South,Sports,6,688.75,0.32,Tabitha,Cash,NaN,NaN,2024-09-18,marilyn547@gmail.com,0774478500,5,Late delivery,2810.10
2,ORD000003,CUST11646,Paul Adams,Female,43,West,Health & Beauty,17,2327.62,0.37,Ian,Mobile Money,SME,Malindi,2023-07-07,NaN,0710826636,3,Highly recommended,24928.81
3,ORD000004,CUST66427,Chris Fox,Male,75,East,Furniture,5,1477.19,0.27,Brian,Mobile Money,Wholesale,Naivasha,2024-02-11,charlotte217@gmail.com,0761837969,5,Product damaged,5391.74
4,ORD000005,CUST55342,Nancy Njoroge,Male,71,East,NaN,-16,253.64,0.26,Steve,Bank Transfer,SME,Embu,2024-02-15,logan1615@gmail.com,0752633078,4,Average experience,-3003.10
5,ORD000006,CUST98919,Alex Ryan,Female,69,Central,Home Appliances,18,2179.50,0.36,Paul,Debit Card,Government,Nyeri,2024-03-20,kyle6091@gmail.com,0773139931,4,Wrong item,25107.84
6,ORD000007,CUST10078,Thomas Harris,Female,38,West,Home Appliances,20,1108.99,0.02,Martin,Credit Card,Retail,Kitale,2024-06-04,billy9665@gmail.com,0775325391,4,Late delivery,21736.20
7,ORD000008,CUST11133,Lisa Webb,Male,50,Central,Electronics,9,1811.75,0.38,Edwin,Debit Card,Retail,Mombasa,2025-03-25,alex9174@gmail.com,0759815442,1,Highly recommended,10109.57
8,ORD000009,CUST32507,Angela Brooks,Female,34,East,Furniture,11,2274.12,0.03,Terry,Credit Card,Wholesale,Kisii,2023-02-05,albert9355@gmail.com,0791307297,1,Average experience,24264.86
9,ORD000010,CUST79557,Olivia Morris,Female,20,North,Automotive,1,457.26,0.19,Calvin,Debit Card,Wholesale,Kitale,2023-05-12,ryan7579@gmail.com,0778241027,1,Late delivery,370.38

#### **Step 7: Summary Statistics for Continuous Data**

In [34]:
summary = df[['Quantity', 'UnitPrice', 'Discount', 'Rating', 'Revenue']].agg({
    'count',
    'mean',
    'median',
    'std',
    'var',
    'min',
    'max',
    'skew',
    'kurt'
}).T # summary = summary. transpose()

summary

,count,std,max,var,skew,median,mean,min,kurt
Quantity,60500.0,5.939552,20.0,3.527828e+01,-0.188447,10.000,10.438000,-20.00,-0.456178
UnitPrice,60500.0,8986.800381,299599.0,8.076258e+07,25.141670,1492.995,1879.938648,0.00,671.512696
Discount,60500.0,0.137291,1.5,1.884878e-02,2.715168,0.200,0.204043,0.00,24.153217
Rating,60500.0,1.439952,10.0,2.073462e+00,0.080153,3.000,3.011950,-1.00,-0.786521
Revenue,60500.0,85772.701205,5207464.4,7.356956e+09,31.933420,9257.365,15661.739505,-43496.17,1185.775553

##### **7.1 Clean the Quantity and Rating Variables**

In [35]:
df.loc[df['Rating'] < 0, 'Rating'] = np.nan
df['Rating'] = df['Rating'].fillna(df['Rating'].median())

In [38]:
df.loc[df['Quantity'] < 0, 'Quantity'] = np.nan
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].median())

In [39]:
summary = df[['Quantity', 'UnitPrice', 'Discount', 'Rating', 'Revenue']].agg({
    'count',
    'mean',
    'median',
    'std',
    'var',
    'min',
    'max',
    'skew',
    'kurt'
}).T 

summary

,count,std,max,var,skew,median,mean,min,kurt
Quantity,60500.0,5.768894,20.0,3.328014e+01,-0.005085,11.000,10.528165,1.00,-1.207637
UnitPrice,60500.0,8986.800381,299599.0,8.076258e+07,25.141670,1492.995,1879.938648,0.00,671.512696
Discount,60500.0,0.137291,1.5,1.884878e-02,2.715168,0.200,0.204043,0.00,24.153217
Rating,60500.0,1.434579,10.0,2.058016e+00,0.094007,3.000,3.015785,0.00,-0.812864
Revenue,60500.0,85772.701205,5207464.4,7.356956e+09,31.933420,9257.365,15661.739505,-43496.17,1185.775553

#### **Step 8: Tips for Handling Missing Values**

In [40]:
df.isnull().sum()

OrderID               0
CustomerID            0
CustomerName       5653
Gender             3010
Age                   0
Region             3031
ProductCategory    3032
Quantity              0
UnitPrice             0
Discount              0
SalesRep           3021
PaymentMethod      3015
CustomerSegment    3022
City               3030
OrderDate             0
Email              3012
Phone              3098
Rating                0
Comments           3003
Revenue               0
dtype: int64

##### **8.1 Fill the Missing Values with 'Unknown' for Categorical Variables**

In [44]:
df[['CustomerName', 'Gender', 'Region', 
    'ProductCategory', 
    'SalesRep','PaymentMethod', 
    'CustomerSegment', 
    'City', 'Email', 'Phone']].fillna('Unknown').isnull().sum()

CustomerName       0
Gender             0
Region             0
ProductCategory    0
SalesRep           0
PaymentMethod      0
CustomerSegment    0
City               0
Email              0
Phone              0
dtype: int64

In [46]:
df['Gender'].value_counts()

Gender
Male       29939
Female     27490
Unknown       61
Name: count, dtype: int64

##### **8.2 Fill the Missing Numeric Variables with Median**